#!/bin/bash

realYaml="app.yaml"
refYaml="$realYaml.official"
oldYaml="app.yaml.old"

localRev=$(hg head |grep changeset |sed "s/.*:\s*\(.*\):.*/\1/g")
if [ -f $realYaml ]
then
    echo " >>> WARNING! $realYaml already exists. Renaming to $oldYaml..."
    cp -f $realYaml $oldYaml
    rm $realYaml
fi

if [ "$1" == "" ]
then
    echo "Missing parameter!"
    echo ""
    echo "Please specify either 'bagareader' (for public release) or your own GAE project name."
    echo "E.g. $0 my-dev-project"
else
    if [ "$1" == "bagareader" ]
    then
        echo " >>> Deploying public release to GAE!"
        echo ""

        cp $refYaml $realYaml
        appcfg.py update .
        rm $realYaml

        echo ""
        echo " >>> Public release deployed to GAE!"
    else
        appName=$1

        echo " >>> Deploying private release $localRev to GAE project $appName..."
        echo ""


        echo "#############################################################################" >> $realYaml
        echo "# THIS IS A TEMPORARY $realYaml FILE GENERATED BY $(basename $0)" >> $realYaml
        echo "# CHANGES TO THIS FILE WILL BE IGNORED. MODIFY $refYaml INSTEAD" >> $realYaml
        echo "#############################################################################" >> $realYaml
        cat $refYaml |sed "s/^application:.*/application: $appName/g;s/^version:\(.*\)/version: \1-dev-$localRev/g" >> $realYaml
        echo "#############################################################################" >> $realYaml

        appcfg.py update .
        rm $realYaml

        echo ""
        echo " >>> Private release $localRev deployed to GAE project $appName..."
    fi
fi
